In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

2.2.3


In [4]:
# Createing an Object of the Serise

In [7]:
a=100
print(a,type(a))
s=pd.Series(a)
print(s,type(s))

100 <class 'int'>
0    100
dtype: int64 <class 'pandas.core.series.Series'>


In [8]:
a=13.4
print(a,type(a))
s=pd.Series(a)
print(s,type(s))

13.4 <class 'float'>
0    13.4
dtype: float64 <class 'pandas.core.series.Series'>


In [9]:
a=True
print(a,type(a))
s=pd.Series(a)
print(s,type(s))

True <class 'bool'>
0    True
dtype: bool <class 'pandas.core.series.Series'>


In [10]:
a=2+5j
print(a,type(a))
s=pd.Series(a)
print(s,type(s))

(2+5j) <class 'complex'>
0    2.0+5.0j
dtype: complex128 <class 'pandas.core.series.Series'>


In [12]:
a=100
print(a,type(a))
s=pd.Series(a,dtype=float)
print(s,type(s))

100 <class 'int'>
0    100.0
dtype: float64 <class 'pandas.core.series.Series'>


In [13]:
a=100
print(a,type(a))
s=pd.Series(a,dtype=int)
print(s,type(s))

100 <class 'int'>
0    100
dtype: int64 <class 'pandas.core.series.Series'>


In [15]:
# a=100.34
# print(a,type(a))
# s=pd.Series(a,dtype=int)
# print(s,type(s))
a=int(100.34)
print(a,type(a))
s=pd.Series(a)
print(s,type(s))

100 <class 'int'>
0    100
dtype: int64 <class 'pandas.core.series.Series'>


In [16]:
a="Python"
s=pd.Series(a)
print(s,type(s))

0    Python
dtype: object <class 'pandas.core.series.Series'>


In [17]:
 # Create A Series Onject by using range

In [19]:
r=range(6)
print(r,type(r))
s=pd.Series(r)
print(s,type(s))

range(0, 6) <class 'range'>
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64 <class 'pandas.core.series.Series'>


In [20]:
# Create A Series Onject by using range with programge define index

In [22]:
r=range(6)
s=pd.Series(r,index=["ID1","ID2","ID3","ID4","ID5","ID6"])
print(s,type(s))

ID1    0
ID2    1
ID3    2
ID4    3
ID5    4
ID6    5
dtype: int64 <class 'pandas.core.series.Series'>


In [23]:
s["ID2"]

np.int64(1)

In [26]:
print(s)

ID1    0
ID2    1
ID3    2
ID4    3
ID5    4
ID6    5
dtype: int64


In [27]:
s[0] #Give result because Default indeces presend when given program str indces

C:\Users\dell\AppData\Local\Temp\ipykernel_980\243613605.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]


np.int64(0)

In [30]:
s[3]

C:\Users\dell\AppData\Local\Temp\ipykernel_980\3172538273.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[3]


np.int64(3)

In [31]:
r=range(6)
s=pd.Series(r,index=[1,2,3,4,5,6])
print(s,type(s))

1    0
2    1
3    2
4    3
5    4
6    5
dtype: int64 <class 'pandas.core.series.Series'>


In [33]:
 s[0 ]#Give key error bcs no Default indeces presend

In [37]:
s=pd.Series(range(10,21,2),dtype=float)
print(s,type(s))

0    10.0
1    12.0
2    14.0
3    16.0
4    18.0
5    20.0
dtype: float64 <class 'pandas.core.series.Series'>


In [40]:
s=pd.Series(range(10,21,2),index=["RS","RS","RS","RS","RS","RS"],dtype=float)
print(s,type(s))

RS    10.0
RS    12.0
RS    14.0
RS    16.0
RS    18.0
RS    20.0
dtype: float64 <class 'pandas.core.series.Series'>


In [41]:
s["RS"]

RS    10.0
RS    12.0
RS    14.0
RS    16.0
RS    18.0
RS    20.0
dtype: float64

In [42]:
s[2]

C:\Users\dell\AppData\Local\Temp\ipykernel_980\2635755408.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[2]


np.float64(14.0)

In [43]:
s[0]

C:\Users\dell\AppData\Local\Temp\ipykernel_980\243613605.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]


np.float64(10.0)

In [47]:
 # Create A Series Onject by using list/tuple with default indces
lst=[100,200,300,400,500]
s=pd.Series(lst)
print(s,type(s))

0    100
1    200
2    300
3    400
4    500
dtype: int64 <class 'pandas.core.series.Series'>


In [44]:
 # Create A Series Onject by using list/tuple with default indces
lst=[100,200,300,400,500]
s=pd.Series(lst,dtype=float)
print(s,type(s))

0    100.0
1    200.0
2    300.0
3    400.0
4    500.0
dtype: float64 <class 'pandas.core.series.Series'>


In [46]:
lst=[100,200,300,400,500]
s=pd.Series(lst,index=[1,2,3,4,5],dtype=float)
print(s,type(s))

1    100.0
2    200.0
3    300.0
4    400.0
5    500.0
dtype: float64 <class 'pandas.core.series.Series'>


In [48]:

lst=[100,200,300,400,500]
s=pd.Series(lst,index=[int(x) for x in range(5,10)],dtype=float)
print(s,type(s))

5    100.0
6    200.0
7    300.0
8    400.0
9    500.0
dtype: float64 <class 'pandas.core.series.Series'>


In [49]:

lst=[100,200,300,400,500]
s=pd.Series(lst,index=["ID"+str(int(x)) for x in range(5,10)],dtype=float)
print(s,type(s))

ID5    100.0
ID6    200.0
ID7    300.0
ID8    400.0
ID9    500.0
dtype: float64 <class 'pandas.core.series.Series'>


In [50]:
tup=(100,200,300,400,500)
s=pd.Series(lst,index=["ID"+str(int(x)) for x in range(5,10)],dtype=float)
print(s,type(s))

ID5    100.0
ID6    200.0
ID7    300.0
ID8    400.0
ID9    500.0
dtype: float64 <class 'pandas.core.series.Series'>


In [51]:
s1={100,200,300,400,500}
print(s1,type(s1))

{400, 100, 500, 200, 300} <class 'set'>


In [52]:
s=pd.Series(s1)
print(s)

TypeError: 'set' type is unordered

In [53]:
s1={100,200,300,400,500}
print(s1,type(s1))
s2=list(s1)
print(s2,type(s2))
s=pd.Series(s2)
print(s)

{400, 100, 500, 200, 300} <class 'set'>
[400, 100, 500, 200, 300] <class 'list'>
0    400
1    100
2    500
3    200
4    300
dtype: int64


In [55]:
 # Create A Series Onject by using dict with default indces
d1={10:"Pythomn",20:"Java",30:"ML",40:"AI",50:"ML"}
print(d1,type(d1))

{10: 'Pythomn', 20: 'Java', 30: 'ML', 40: 'AI', 50: 'ML'} <class 'dict'>


In [56]:
 # Create A Series Onject by using dict with default indces
d1={10:"Pythomn",20:"Java",30:"ML",40:"AI",50:"ML"}
print(d1,type(d1))
print("="*50)
s=pd.Series(d1)
print(s,type(s))

{10: 'Pythomn', 20: 'Java', 30: 'ML', 40: 'AI', 50: 'ML'} <class 'dict'>
10    Pythomn
20       Java
30         ML
40         AI
50         ML
dtype: object <class 'pandas.core.series.Series'>


In [58]:
s[10]

'Pythomn'

In [59]:
s[50]

'ML'

In [60]:
s[0]

KeyError: 0

In [61]:
print(s)

10    Pythomn
20       Java
30         ML
40         AI
50         ML
dtype: object


In [62]:
s[10:30]

Series([], dtype: object)

In [65]:
d={"crs1":["Python","Numpy","Django"],"crs2":["Java","Spring","Hibernate"]}
print(d,type(d))
for key ,value in d.items():
    print("{}-->{}".format(key,value))

{'crs1': ['Python', 'Numpy', 'Django'], 'crs2': ['Java', 'Spring', 'Hibernate']} <class 'dict'>
crs1-->['Python', 'Numpy', 'Django']
crs2-->['Java', 'Spring', 'Hibernate']


In [66]:
d={"crs1":["Python","Numpy","Django"],"crs2":["Java","Spring","Hibernate"]}
for key ,value in d.items():
    print("{}-->{}".format(key,value))
print("="*50)
s=pd.Series(d)
print(s)

crs1-->['Python', 'Numpy', 'Django']
crs2-->['Java', 'Spring', 'Hibernate']
crs1      [Python, Numpy, Django]
crs2    [Java, Spring, Hibernate]
dtype: object


In [67]:
s[0]

C:\Users\dell\AppData\Local\Temp\ipykernel_980\243613605.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]


['Python', 'Numpy', 'Django']

In [68]:
s["crs2"]

['Java', 'Spring', 'Hibernate']

In [71]:
import numpy as np
a=np.array((100,200,300,400,500))
print(a,type(a))
s=pd.Series(a)
print(s,type(s))

[100 200 300 400 500] <class 'numpy.ndarray'>
0    100
1    200
2    300
3    400
4    500
dtype: int64 <class 'pandas.core.series.Series'>


In [72]:
import numpy as np
a=np.array((100,200,300,400,500))
print(a,type(a))
s=pd.Series(a,dtype=float)
print(s,type(s))

[100 200 300 400 500] <class 'numpy.ndarray'>
0    100.0
1    200.0
2    300.0
3    400.0
4    500.0
dtype: float64 <class 'pandas.core.series.Series'>


In [80]:
a=np.array((100,200,300,400,500))
print(a,type(a))
print("="*50)
s=pd.Series(a,index=["ID"+str(int(x)) for x in range(1,len(a)+1)],dtype=float)
print(s,type(s))

[100 200 300 400 500] <class 'numpy.ndarray'>
ID1    100.0
ID2    200.0
ID3    300.0
ID4    400.0
ID5    500.0
dtype: float64 <class 'pandas.core.series.Series'>


In [87]:
a=np.array((100,200,300,400,500))
print(a,type(a))
print("="*50)
s=pd.Series(a,index=["ID"+str(int(x)) for x in np.arange(2,len(a)+2)],dtype=float)
print(s,type(s))

[100 200 300 400 500] <class 'numpy.ndarray'>
ID2    100.0
ID3    200.0
ID4    300.0
ID5    400.0
ID6    500.0
dtype: float64 <class 'pandas.core.series.Series'>
